#!/usr/bin/env bash
set -eo pipefail; [[ $FIGURE_TRACE ]] && set -x

if [[ ! -f /etc/sudoers.d/figure-nginx ]]; then
  case "$FIGURE_DISTRO" in
    ubuntu)
      echo "%figure ALL=(ALL) NOPASSWD:/etc/init.d/nginx reload" >> /etc/sudoers.d/figure-nginx
      ;;

    opensuse)
      echo "%figure ALL=(ALL) NOPASSWD:/sbin/service nginx reload" >> /etc/sudoers.d/figure-nginx
      ;;
  esac

  chmod 0440 /etc/sudoers.d/figure-nginx
fi

# if figure.conf has not been created, create it
if [[ ! -f /etc/nginx/conf.d/figure.conf ]]; then
  cat<<EOF > /etc/nginx/conf.d/figure.conf
include $FIGURE_ROOT/*/nginx.conf;

ssl_session_cache shared:SSL:20m;
ssl_session_timeout 10m;

ssl_ciphers EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;
ssl_protocols TLSv1.2 TLSv1.1 TLSv1;

ssl_prefer_server_ciphers on;

EOF
fi

cat<<EOF > /etc/nginx/nginx.conf
user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
  worker_connections 768;
}

http {
  server_tokens off;
  sendfile on;
  tcp_nopush on;
  tcp_nodelay on;
  keepalive_timeout 65;
  types_hash_max_size 2048;

  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  access_log /var/log/nginx/access.log;
  error_log /var/log/nginx/error.log;

  gzip on;
  gzip_disable "msie6";

  include /etc/nginx/conf.d/*.conf;
  include /etc/nginx/sites-enabled/*;
}

EOF

echo 'server_names_hash_bucket_size 512;' >| /etc/nginx/conf.d/server_names_hash_bucket_size.conf

case "$FIGURE_DISTRO" in
  ubuntu)
    /etc/init.d/nginx start
    ;;

  opensuse)
    /sbin/service nginx start
    ;;
esac
