#!/usr/bin/env bash
set -eo pipefail; [[ $FIGURE_TRACE ]] && set -x

APP="$1"; PORT="$2"; IP="$3"

set +e; NO_VHOST=$(figure config:get $APP NO_VHOST); set -e

if [[ -n "$NO_VHOST" ]]; then
  echo "-----> NO_VHOST config detected"
elif [[ ! -f "$FIGURE_ROOT/$APP/VHOST" ]]; then
  figure domains:setup $APP
fi

figure nginx:build-config $APP $PORT $IP
