#!/usr/bin/env bash
set -eo pipefail; [[ $FIGURE_TRACE ]] && set -x

case "$FIGURE_DISTRO" in
  ubuntu)
    sudo /etc/init.d/nginx reload > /dev/null
    ;;

  opensuse)
    sudo /sbin/service nginx reload > /dev/null
    ;;
esac
