#!/usr/bin/env bash
set -eo pipefail; [[ $FIGURE_TRACE ]] && set -x

if [[ ! -f  "$FIGURE_ROOT/HOSTNAME" ]]; then
  hostname -f > $FIGURE_ROOT/HOSTNAME
fi

if [[ ! -f  "$FIGURE_ROOT/VHOST" ]]; then
  [[ $(dig +short "$(< "$FIGURE_ROOT/HOSTNAME")") ]] && cp "$FIGURE_ROOT/HOSTNAME" "$FIGURE_ROOT/VHOST"
fi
